### ISSUE TITLE
Jquery 503 Fehler

### ISSUE THREAD

**Issue by Suchty112** [eaglefsd/ASL#5]
![jquery](https://cloud.githubusercontent.com/assets/1109899/8302603/edad1922-1997-11e5-9c19-5e8689f3d616.PNG)
![kilu](https://cloud.githubusercontent.com/assets/1109899/8302602/edab7a68-1997-11e5-82dc-68698649427f.PNG)
Ich würde vorschlagen das JQueryCookie auch auf github zu tun und nicht auf den webspace von kilu.. dadurch enstehen aktuell einige ladezeiten :) daher auch kein pullrequest sondern ein issue

**Comment by eaglefsd** [comment]
a21cdf2960a80e1b62262de85036bd51ee88265e
